[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install uv", "uv sync --locked"]

[phases.build]
cmds = ["uv run reflex export --frontend-only --no-zip"]

[start]
cmd = "uv run reflex run --env prod"
